title: GravPor
description: Game / Blog / Memo
theme: null
markdown: kramdown
permalink: pretty

collections:
  blog:
    output: true
    permalink: /blog/:name/
  memo:
    output: true
    permalink: /memo/:name/
